-- MySQL Script generated by MySQL Workbench
-- Thu Aug 15 18:05:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
DROP DATABASE IF EXISTS nhsbank;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nhsbank
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nhsbank` ;

-- -----------------------------------------------------
-- Schema nhsbank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nhsbank` DEFAULT CHARACTER SET utf8 ;
USE `nhsbank` ;

-- -----------------------------------------------------
-- Table `nhsbank`.`branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`branch` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`branch` (
                                                  `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                  `name` VARCHAR(45) NULL DEFAULT NULL,
                                                  `assets` VARCHAR(45) NULL DEFAULT NULL,
                                                  PRIMARY KEY (`id`),
                                                  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
    ENGINE = InnoDB
    AUTO_INCREMENT = 4
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`tier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`tier` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`tier` (
                                                `id` INT(11) NOT NULL,
                                                `name` VARCHAR(45) NULL DEFAULT NULL,
                                                `overdraft_limit` DECIMAL(18,2) NULL DEFAULT NULL,
                                                `limit_transaction` DECIMAL(18,2) NULL DEFAULT NULL,
                                                PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`account` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`account` (
                                                   `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                   `account_number` VARCHAR(45) NULL DEFAULT NULL,
                                                   `account_type` TINYINT(4) NULL DEFAULT NULL,
                                                   `balance` DECIMAL(18,9) NULL DEFAULT NULL,
                                                   `open_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
                                                   `branch_id` INT(11) NULL DEFAULT NULL,
                                                   `status` INT(11) NULL DEFAULT NULL,
                                                   `tier_id` INT(11) NULL,
                                                   PRIMARY KEY (`id`),
                                                   UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
                                                   INDEX `fk_account_branch1_idx` (`branch_id` ASC) ,
                                                   INDEX `fk_account_tier1_idx` (`tier_id` ASC) ,
                                                   CONSTRAINT `fk_account_branch1`
                                                       FOREIGN KEY (`branch_id`)
                                                           REFERENCES `nhsbank`.`branch` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_account_tier1`
                                                       FOREIGN KEY (`tier_id`)
                                                           REFERENCES `nhsbank`.`tier` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB
    AUTO_INCREMENT = 58
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`membership` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`membership` (
                                                      `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                      `name` VARCHAR(45) NULL DEFAULT NULL,
                                                      `description` TEXT NULL DEFAULT NULL,
                                                      `saving_limit` DECIMAL(18,2) NULL DEFAULT NULL,
                                                      `loan_limit` DECIMAL(18,2) NULL DEFAULT NULL,
                                                      PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 5
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`customer` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`customer` (
                                                    `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                    `firstname` NVARCHAR(45) NULL,
                                                    `lastname` NVARCHAR(45) NULL DEFAULT NULL,
                                                    `dateOfBirth` DATETIME NULL DEFAULT NULL,
                                                    `address_id` INT(11) NULL DEFAULT NULL,
                                                    `email` VARCHAR(255) NULL DEFAULT NULL,
                                                    `phone` VARCHAR(12) NULL DEFAULT NULL,
                                                    `social_security_number` VARCHAR(20) NULL DEFAULT NULL,
                                                    `occupation` VARCHAR(45) NULL DEFAULT NULL,
                                                    `membership` TINYINT(4) NULL DEFAULT NULL,
                                                    `membership_id` INT(11) NOT NULL,
                                                    PRIMARY KEY (`id`),
                                                    UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
                                                    INDEX `fk_customer_membership1_idx` (`membership_id` ASC) ,
                                                    CONSTRAINT `fk_customer_membership1`
                                                        FOREIGN KEY (`membership_id`)
                                                            REFERENCES `nhsbank`.`membership` (`id`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION)
    ENGINE = InnoDB
    AUTO_INCREMENT = 23
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`account_holder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`account_holder` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`account_holder` (
                                                          `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                          `customer_id` INT(11) NOT NULL,
                                                          `account_id` INT(11) NOT NULL,
                                                          `is_default` TINYINT(4) NULL DEFAULT NULL,
                                                          PRIMARY KEY (`id`, `customer_id`, `account_id`),
                                                          INDEX `fk_customer_has_account_account1_idx` (`account_id` ASC) ,
                                                          INDEX `fk_customer_has_account_customer1_idx` (`customer_id` ASC) ,
                                                          CONSTRAINT `fk_customer_has_account_account1`
                                                              FOREIGN KEY (`account_id`)
                                                                  REFERENCES `nhsbank`.`account` (`id`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION,
                                                          CONSTRAINT `fk_customer_has_account_customer1`
                                                              FOREIGN KEY (`customer_id`)
                                                                  REFERENCES `nhsbank`.`customer` (`id`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION)
    ENGINE = InnoDB
    AUTO_INCREMENT = 45
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`loan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`loan` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`loan` (
                                                `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                `customer_id` INT(11) NOT NULL,
                                                `type` TINYINT(4) NULL DEFAULT NULL,
                                                `amount` DECIMAL(18,9) UNSIGNED NULL DEFAULT NULL,
                                                `interest_rate` DECIMAL(9,2) UNSIGNED NULL DEFAULT NULL,
                                                `term` INT(10) UNSIGNED NULL DEFAULT NULL,
                                                `approval_date` DATETIME NULL DEFAULT NULL,
                                                `status` TINYINT(4) NULL DEFAULT NULL,
                                                `repayment` VARCHAR(45) NULL DEFAULT NULL,
                                                `branch_id` INT(11) NOT NULL,
                                                `duration` INT(11) NULL DEFAULT NULL,
                                                `disbursement_account_number` VARCHAR(45) NULL DEFAULT NULL,
                                                `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
                                                PRIMARY KEY (`id`, `customer_id`),
                                                UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
                                                INDEX `fk_loan_customer1_idx` (`customer_id` ASC) ,
                                                INDEX `fk_loan_branch1_idx` (`branch_id` ASC) ,
                                                CONSTRAINT `fk_loan_branch1`
                                                    FOREIGN KEY (`branch_id`)
                                                        REFERENCES `nhsbank`.`branch` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_loan_customer1`
                                                    FOREIGN KEY (`customer_id`)
                                                        REFERENCES `nhsbank`.`customer` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB
    AUTO_INCREMENT = 6
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`login` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`login` (
                                                 `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                 `username` VARCHAR(255) NULL DEFAULT NULL,
                                                 `password` VARCHAR(255) NULL DEFAULT NULL,
                                                 `PIN` CHAR(6) NULL DEFAULT NULL,
                                                 `customer_id` INT(11) NOT NULL,
                                                 PRIMARY KEY (`id`, `customer_id`),
                                                 INDEX `fk_login_customer1_idx` (`customer_id` ASC) ,
                                                 CONSTRAINT `fk_login_customer1`
                                                     FOREIGN KEY (`customer_id`)
                                                         REFERENCES `nhsbank`.`customer` (`id`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB
    AUTO_INCREMENT = 31
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`transaction` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`transaction` (
                                                       `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                       `account_id` INT(11) NOT NULL,
                                                       `transaction_type` TINYINT(4) NULL DEFAULT NULL,
                                                       `amount` DECIMAL(18,9) NULL DEFAULT NULL,
                                                       `description` VARCHAR(255) NULL DEFAULT NULL,
                                                       `reference_number` VARCHAR(45) NULL DEFAULT NULL,
                                                       `status` TINYINT(4) NULL DEFAULT NULL,
                                                       `transaction_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
                                                       PRIMARY KEY (`id`),
                                                       INDEX `fk_transaction_account1_idx` (`account_id` ASC) ,
                                                       CONSTRAINT `fk_transaction_account1`
                                                           FOREIGN KEY (`account_id`)
                                                               REFERENCES `nhsbank`.`account` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB
    AUTO_INCREMENT = 141
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`payment` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`payment` (
                                                   `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                   `loan_id` INT(11) NOT NULL,
                                                   `amount` DECIMAL(2,0) NULL DEFAULT NULL,
                                                   `payment_date` DATETIME NULL DEFAULT NULL,
                                                   `payment_status` VARCHAR(45) NULL DEFAULT NULL,
                                                   `transaction_id` INT(11) NOT NULL,
                                                   PRIMARY KEY (`id`, `loan_id`, `transaction_id`),
                                                   INDEX `fk_payment_loan1_idx` (`loan_id` ASC) ,
                                                   INDEX `fk_payment_transaction1_idx` (`transaction_id` ASC) ,
                                                   CONSTRAINT `fk_payment_loan1`
                                                       FOREIGN KEY (`loan_id`)
                                                           REFERENCES `nhsbank`.`loan` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_payment_transaction1`
                                                       FOREIGN KEY (`transaction_id`)
                                                           REFERENCES `nhsbank`.`transaction` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`savings_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`savings_info` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`savings_info` (
                                                        `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                        `interest_rate` DECIMAL(4,2) NULL DEFAULT NULL,
                                                        `type` TINYINT(4) NULL DEFAULT NULL,
                                                        `rollover` TINYINT(4) NULL DEFAULT NULL,
                                                        `term` INT(11) NULL DEFAULT NULL,
                                                        `account_id` INT(11) NOT NULL,
                                                        `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
                                                        `beneficiary_account_id` INT(11) NULL DEFAULT NULL,
                                                        PRIMARY KEY (`id`, `account_id`),
                                                        INDEX `fk_savings_infor_account1_idx` (`account_id` ASC) ,
                                                        CONSTRAINT `fk_savings_infor_account1`
                                                            FOREIGN KEY (`account_id`)
                                                                REFERENCES `nhsbank`.`account` (`id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB
    AUTO_INCREMENT = 32
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`savings_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`savings_log` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`savings_log` (
                                                       `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                       `amount` DECIMAL(4,2) NULL DEFAULT NULL,
                                                       `create_at` DATE NULL DEFAULT CURRENT_TIMESTAMP(),
                                                       `detail` TEXT NULL DEFAULT NULL,
                                                       `savings_infor_id` INT(11) NOT NULL,
                                                       `savings_infor_account_id` INT(11) NOT NULL,
                                                       PRIMARY KEY (`id`, `savings_infor_id`, `savings_infor_account_id`),
                                                       INDEX `fk_savings_log_savings_infor1_idx` (`savings_infor_id` ASC, `savings_infor_account_id` ASC) ,
                                                       CONSTRAINT `fk_savings_log_savings_infor1`
                                                           FOREIGN KEY (`savings_infor_id` , `savings_infor_account_id`)
                                                               REFERENCES `nhsbank`.`savings_info` (`id` , `account_id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`transaction_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`transaction_log` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`transaction_log` (
                                                           `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                           `transaction_id` INT(11) NOT NULL,
                                                           `detail` VARCHAR(255) NULL DEFAULT NULL,
                                                           `log_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
                                                           PRIMARY KEY (`id`),
                                                           INDEX `fk_transaction_log_transaction1_idx` (`transaction_id` ASC) ,
                                                           CONSTRAINT `fk_transaction_log_transaction1`
                                                               FOREIGN KEY (`transaction_id`)
                                                                   REFERENCES `nhsbank`.`transaction` (`id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`transfer` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`transfer` (
                                                    `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                    `transaction_id` INT(11) NOT NULL,
                                                    `account_id` INT(11) NOT NULL,
                                                    `status` VARCHAR(45) NULL DEFAULT 'PENDING',
                                                    `message` TEXT NULL DEFAULT NULL,
                                                    PRIMARY KEY (`id`, `transaction_id`, `account_id`),
                                                    INDEX `fk_transfer_transaction1_idx` (`transaction_id` ASC) ,
                                                    INDEX `fk_transfer_account1_idx` (`account_id` ASC) ,
                                                    CONSTRAINT `fk_transfer_account1`
                                                        FOREIGN KEY (`account_id`)
                                                            REFERENCES `nhsbank`.`account` (`id`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION,
                                                    CONSTRAINT `fk_transfer_transaction1`
                                                        FOREIGN KEY (`transaction_id`)
                                                            REFERENCES `nhsbank`.`transaction` (`id`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION)
    ENGINE = InnoDB
    AUTO_INCREMENT = 138
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nhsbank`.`savings_setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`savings_setting` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`savings_setting` (
                                                           `id` INT NOT NULL,
                                                           `term` SMALLINT NULL,
                                                           `interest_rate` FLOAT NULL,
                                                           PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nhsbank`.`loan_setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhsbank`.`loan_setting` ;

CREATE TABLE IF NOT EXISTS `nhsbank`.`loan_setting` (
                                                        `id` INT NOT NULL,
                                                        `term` SMALLINT NULL,
                                                        `interest_rate` FLOAT NULL,
                                                        PRIMARY KEY (`id`))
    ENGINE = InnoDB;

USE `nhsbank` ;

-- -----------------------------------------------------
-- function unpaidMonthlyLoanCount
-- -----------------------------------------------------

USE `nhsbank`;
DROP function IF EXISTS `nhsbank`.`unpaidMonthlyLoanCount`;

DELIMITER $$
USE `nhsbank`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `unpaidMonthlyLoanCount`(loan_id_params int
) RETURNS int(11)
    READS SQL DATA
    DETERMINISTIC
begin
    declare latestPayment datetime;
    declare currentDate datetime default now();
    declare unpaidMonthCount int default 0;
    declare date_ref datetime;

    select payment.payment_date into latestPayment from payment
    where payment.loan_id=loan_id_params order by payment_date desc limit 1;

    if latestPayment is not null then
        set date_ref=latestPayment;
    else
        select loan.approval_date into date_ref from loan  where loan.id=loan_id_params;
    end if;
    while datediff(currentDate,date_ref)>0 do
            set unpaidMonthCount=unpaidMonthCount+1;
            set date_ref=DATE_ADD(date_ref,INTERVAL 1 MONTH);
        end while;
    return unpaidMonthCount;
end$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
